module.exports = [
  [/^chocolate chip cookie/i, 21, '🍪'],
  [/^glass of wine/i, 13, '🍷'],
  [/^wine glass/i, 10, '🍷'],
  [/^light bulb/i, 10, '💡'],
  [/^lightbulb/i, 9, '💡'],
  [/^calendar/i, 8, '📅'],
  [/^drinking/i, 8, '🍻'],
  [/^computer/i, 8, '💻'],
  [/^hot dog/i, 7, '🌭'],
  [/^monkey/i, 6, '🐵'],
  [/^cookie/i, 6, '🍪'],
  [/^hotdog/i, 6, '🌭'],
  [/^laptop/i, 6, '💻'],
  [/^train/i, 5, '🚄'],
  [/^shite/i, 5, '💩'],
  [/^sleep/i, 5, '💤'],
  [/^ghost/i, 5, '👻'],
  [/^beers/i, 5, '🍻'],
  [/^light/i, 5, '💡'],
  [/^beer/i, 4, '🍺'],
  [/^taco/i, 4, '🌮'],
  [/^date/i, 4, '📅'],
  [/^poop/i, 4, '💩'],
  [/^butt/i, 4, '🍑'],
  [/^wine/i, 4, '🍷'],
  [/^idea/i, 4, '💡'],
  [/^cat/i, 3, '🐱'],
  [/^tea/i, 3, '🍵'],
  [/^eye/i, 3, '👁'],
  [/^man/i, 3, '👨'],
  [/^up/i, 2, '🆙'],
  [/^us/i, 2, '🇺🇸'],
  [/^t/i, 1, '🍵'],
  [/^i/i, 1, '👁'],
];
