module.exports = [
  [/^chocolate chip cookie/i, 21, '🍪'],
  [/^christmas tree/i, 14, '🎄'],
  [/^glass of wine/i, 13, '🍷'],
  [/^hahahahaha/i, 10, '😆'],
  [/^wine glass/i, 10, '🍷'],
  [/^light bulb/i, 10, '💡'],
  [/^christmas/i, 9, '🎄'],
  [/^lightbulb/i, 9, '💡'],
  [/^drinking/i, 8, '🍻'],
  [/^calendar/i, 8, '📅'],
  [/^computer/i, 8, '💻'],
  [/^hahahaha/i, 8, '😆'],
  [/^password/i, 8, '🙊'],
  [/^hot dog/i, 7, '🌭'],
  [/^running/i, 7, '🏃'],
  [/^hotdog/i, 6, '🌭'],
  [/^e-mail/i, 6, '📧'],
  [/^cookie/i, 6, '🍪'],
  [/^monkey/i, 6, '🐵'],
  [/^laptop/i, 6, '💻'],
  [/^seamus/i, 6, '🌊🦄'],
  [/^knows/i, 5, '👃'],
  [/^train/i, 5, '🚄'],
  [/^x-mas/i, 5, '🎄'],
  [/^angry/i, 5, '😡'],
  [/^anger/i, 5, '😡'],
  [/^think/i, 5, '🤔'],
  [/^beers/i, 5, '🍻'],
  [/^email/i, 5, '📧'],
  [/^light/i, 5, '💡'],
  [/^block/i, 5, '▆'],
  [/^shite/i, 5, '💩'],
  [/^sleep/i, 5, '💤'],
  [/^ghost/i, 5, '👻'],
  [/^idea/i, 4, '💡'],
  [/^taco/i, 4, '🌮'],
  [/^haha/i, 4, '😆'],
  [/^xmas/i, 4, '🎄'],
  [/^buzz/i, 4, '🐝'],
  [/^okay/i, 4, '👌'],
  [/^okey/i, 4, '👌'],
  [/^nose/i, 4, '👃'],
  [/^butt/i, 4, '🍑'],
  [/^wine/i, 4, '🍷'],
  [/^poop/i, 4, '💩'],
  [/^beer/i, 4, '🍺'],
  [/^date/i, 4, '📅'],
  [/^zzz/i, 3, '💤'],
  [/^man/i, 3, '👨'],
  [/^cat/i, 3, '🐱'],
  [/^tea/i, 3, '🍵'],
  [/^bee/i, 3, '🐝'],
  [/^eye/i, 3, '👁'],
  [/^ran/i, 3, '🏃'],
  [/^mad/i, 3, '😡'],
  [/^run/i, 3, '🏃'],
  [/^zz/i, 2, '💤'],
  [/^ok/i, 2, '👌'],
  [/^up/i, 2, '🆙'],
  [/^us/i, 2, '🇺🇸'],
  [/^i/i, 1, '👁'],
  [/^b/i, 1, '🐝'],
  [/^t/i, 1, '🍵'],
];
